{% set name = "pyflame" %}
{% set version = "1.6.3" %}
{% set checksum = "9b7c09302f7b7ce27b57c45b78494a1170cad1e994ec8168c1bb1c6175c217b8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/uber/pyflame/archive/v{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  skip: true  # [not linux]
  skip: true  # [py>36]

requirements:
  build:
    - autoconf
    - automake
    - libtool
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python

  run:
    - python

test:
  commands:
    - test -f $PREFIX/bin/pyflame

about:
  home: https://pyflame.readthedocs.io/en/latest/
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: Pyflame is a ptracing profiler for Python.
  dev_url: https://github.com/uber/pyflame

extra:
  recipe-maintainers:
    - eklitzke
    - xhochy
