{% set name = "pyflame" %}
{% set version = "1.6.1" %}
{% set checksum = "648a956a460a5d01abbfbe3cf37c6ee61f045a683a13e21c704a5b2eef356c6f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/uber/pyflame/archive/v{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  skip: true  # [not linux]
  skip: true  # [py>36]

requirements:
  build:
    - autoconf
    - automake
    - libtool
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python

  run:
    - python

test:
  commands:
    - test -f $PREFIX/bin/pyflame

about:
  home: https://pyflame.readthedocs.io/en/latest/
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: Pyflame is a ptracing profiler for Python.
  dev_url: https://github.com/uber/pyflame

extra:
  recipe-maintainers:
    - eklitzke
    - xhochy
